### PR TITLE
Note the default checkouts for jobs vs deployments

### PR DESCRIPTION
**Pull request by zippy1981**
If you inherit  a multi-stage pre-existing pipeline it can be non-obvious why some stages check out and some don't if some of your jobs in some stages do deployments from `jobs.job` instead of `jobs.deploy` and this is the page you turn to first.

### CODE REVIEW

**Comment by steved0x** [comment]
Docs Build status updates of commit _[d6a09e7](https://github.com/zippy1981/azure-devops-yaml-schema/commits/d6a09e7e39d28cefc6fe183b2566e2604733d395)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[content/steps-checkout.md](https://github.com/zippy1981/azure-devops-yaml-schema/blob/patch-1/content/steps-checkout.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/49a3200c-f283-8dd5-6eb3-056af594a9a5/202209232141422235-42/BuildReport?accessString=0f5e6b65201741687359e206b51ec7757ed5e235236603a1dd432e8afcf3b9bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/49a3200c-f283-8dd5-6eb3-056af594a9a5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by steved0x** [comment]
@zippy1981 This is a good PR. Some of those parts are generated from the YAML schema so I need to make some changes behind the scenes so it doesn't get overwritten the next time the tooling runs. I will get this updated next week and merge your PR. Thank you.

**Comment by zippy1981** [comment]
@steved0x is this still on track to get merged?

**Comment by steved0x** [comment]
@zippy1981 The new format for the YAML schema is published. The YAML schema reference now combines autogenerated portions, combined with user-editable content that can be updated by community contributors. The look and feel of the YAML Schema pages is the same, but behind the scenes the markdown down format is different. Unfortunately that led to a big merge conflict with your PR that when I resolved, resulted in no changes (since I had resolved these issues when I migrated to the new format). Please see the updated checkout article: https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout

The YAML syntax snippet is updated for the different versions, and in the properties table, there is additional detail that you provided.

For 2019 & 2019.1 that YAML snippet is:
```
- checkout: string # Required as first property. Whether or not to check out the repository containing this pipeline definition.
```

For 2020 and higher it is:
```
- checkout: string # Required as first property. Configures checkout for the specified repository.
```

The property description for 2020 and higher is updated with the info that you provided:
image

This should be live momentarily. Thank you for making this contribution and I am sorry that I wasn't able to merge your PR.

**Pull request closed without merging**
