### PR TITLE
NuGet Package Source Mapping Problem

### PR DESCRIPTION
**Pull request by chkoella**
https://github.com/MicrosoftDocs/azure-devops-yaml-schema/issues/100
- Moved the Important Notice on top of article
- Added the section "Why am I getting NU1507 warnings ..."

### CODE REVIEW

**Comment by chkoella** [comment]
@microsoft-github-policy-service agree

**Comment by chkoella** [comment]
Is there any action needed from my site for the PR to proceed?

**Comment by WilliamAntonRohm** [comment]
@chkoella -- Christian, your PR is in motion and no further action is necessary on your part.  It will be merged and closed when the review is done.

**Comment by steved0x** [comment]
@chkoella Thank you for your PR. I made a few small changes (moved the note slightly and added it to the remarks for that task input) and it should be live soon. Thank you.

**Pull request merged**
