### PR TITLE
[AzureSpringCloudV0] Rename Azure Spring Cloud to Azure Spring Apps

### PR DESCRIPTION
**Pull request by yitaopan**
Thank you for your contribution. Please see the README.MD in this repo for details on how to contribute.

- [ ] Are you creating a new task article? If yes, STOP. New task articles are auto-generated when the new task is deployed to an Azure DevOps sprint, including all task inputs, aliases, defaults, and allowed values. Once the task deploys and the article is generated, you can make a PR to add examples, remarks, and descriptions. If you have a readme.md file in the tasks repo for your new task, that content will be picked up as well. If you have a section in the readme.md file that explains what makes this new version of the task different than the previous version, that is greatly appreciated.
- [ ] Are you editing a task or YAML schema definition article? We welcome your contributions to content that is contained within "editable-content" tags. Any contributions outside of an "editable-content" tag won't be merged as these articles are auto-generated (and auto-updated when new properties or inputs are deployed), with the exception of the content inside "editable-content" tags.

### CODE REVIEW

**Comment by steved0x** [comment]
@yitaopan Please ping me when this PR is moved from draft to that I can review and get it published. Thank you.

**Comment by yitaopan** [comment]
Hi @steved0x thanks! I would like to ask some questions first. I am trying to rename the original "Azure Spring Cloud" to "Azure Spring Apps", which has already finished in the ADO task source code. To my understanding, I can only change the content in "editable", but there are some content outside of editable that also needs to be changed. Can you please help me understand what can I do in this case? Thank you very much!

**Comment by steved0x** [comment]
@yitaopan Sorry for this delay. I will send you an email. When it is changed in the task source code, it will automatically change in the docs. For the Azure DevOps Services version of the task documentation, it looks like it has already changed (although the name of the task is still `AzureSpringcloud@0`. However, the Azure DevOps Server 2022 version of the task that shipped with 2022 still has the task.json from that version, with the Azure Spring Cloud naming. I can get that fixed.

**Comment by yitaopan** [comment]
@steved0x Thank you very much for your explanation! The content changed in the editable section should be enough, I have replied to your email and this PR is ready for review. Can you please help take a look at this? Thanks!

**Review by steved0x — APPROVED** [review]

**Pull request merged**
